; [shop_sys_info]
; enterpriseName = 地鲟科技
; shopBaseUrl = https://shop-api-crs.vchangyi.com
; enterpriseId = 133719584357376
; enterpriseHash = a25276e4d2bafe38c3746e20c12db1ed
; jumpServerIp = http://9.104.219.79:33334
; userId = 133851444048960

[console_sys_info]
consoleLoginUrl = https://crs-api.vchangyi.com
;consoleBaseUrl = https://console-api-crs.vchangyi.com
consoleBaseUrl = https://crs-api.vchangyi.com
consoleAccount = wanggenggeng@vchangyi.com
consolePassword = aaa3cc3b6945ef65bf7eaeece3ccad61
loginType = 1

[console_sys_info_baize]
enterpriseName = 白泽信息科技
consoleLoginUrl = https://crs-api.vchangyi.com
consoleAccount = xuetong@vchangyi.com
consolePassword = 995bf49049fc670ab62fa320dddef06e
loginType = 1
work_id = 5554C39D7F00000104414CC9C45B3EAC
enterpriseHash = 61fb72b508532bfa698f17b37be7ff9a

[boss_sys_info]
consoleBossUrl = https://boss-test-crs.vchangyi.com
consoleBossAccount = 18800009999
consoleBossPassword = changyi2018
host = crs-api-test.vchangyi.com
[log_level]
;取值：DEBUG INFO WARNING ERROR CRITICAL
logLevel = INFO

[open-api]
crsAuthKey = 64c47fa898f697bf
crsAuthSecret = 8aff1f0d37662d1274d219d2e9db81b6

[console_cyy_info]
enterpriseName = 创业翼
consoleUrl = https://console.dev.v2.chinawip.com
password = muqR*W!k7$r3jrVEv
username = admin