[log_level]
;取值：DEBUG INFO WARNING ERROR CRITICAL
logLevel = INFO

[open-api]
crsAuthKey = 64c47fa898f697bf
crsAuthSecret = 8aff1f0d37662d1274d219d2e9db81b6

[console_cyy_info]
enterpriseName = 创业翼
consoleUrl = https://console.dev.v2.chinawip.com
password = muqR*W!k7$r3jrVEv
username = admin